services:
  postgres:
    image: postgres:16-alpine
    container_name: oms-postgres
    environment:
      POSTGRES_DB: order_management
      POSTGRES_USER: oms
      POSTGRES_PASSWORD: oms
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
